#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
mkdir -p build
task_tmp=$(mktemp -d "$PWD/build/lalr.XXXXXX")
trap 'task_status=$?; if [ "$task_status" -eq 0 ]; then rm -rf "$task_tmp"; else printf "LALR logs retained: %s\n" "$task_tmp" >&2; fi' EXIT
generator=packages/parser/.lake/build/bin/lalrgen
packages/modelica-parser/.lake/build/bin/lalr-tests packages/modelica-parser/grammar/Modelica.ebnf
# The production module is kernel checked and axiom audited by Lake. Compare
# these actual generated bytes with it instead of re-elaborating the same large
# theorem set under another namespace on every gate invocation.
"$generator" --namespace Rumoca.Generated --module ModelicaParser.Generated packages/modelica-parser/grammar/Modelica.ebnf "$task_tmp/Modelica.lean"
"$generator" --namespace Rumoca.Generated --module ModelicaParser.Generated packages/modelica-parser/grammar/Modelica.ebnf "$task_tmp/Again.lean"
cmp "$task_tmp/Modelica.lean" "$task_tmp/Again.lean"
diff -r "$task_tmp/Modelica" "$task_tmp/Again"
cmp "$task_tmp/Modelica.lean" packages/modelica-parser/ModelicaParser/Generated.lean
diff -r "$task_tmp/Modelica" packages/modelica-parser/ModelicaParser/Generated

# Readable recursive EBNF, emitted Lean tables, and kernel execution of those
# actual tables. The emitted completeness consequence quantifies over all words.
printf '%s\n' "s : '(' s ')' s | '';" > "$task_tmp/recursive.ebnf"
# Single-file mode keeps every certificate group in one module so `lake env lean`
# and the `sed` mutation controls below act on one standalone file.
"$generator" --single "$task_tmp/recursive.ebnf" "$task_tmp/Recursive.lean"
cat >> "$task_tmp/Recursive.lean" <<'LEAN'
set_option maxRecDepth 10000 in
example : (Parser.LALR.parse Parser.LALRGenerated.grammar
    Parser.LALRGenerated.tables 100 [0, 0, 1, 1]).isOk = true := by decide +kernel
LEAN
cat >> "$task_tmp/Recursive.lean" <<'LEAN'
#print axioms Parser.LALRGenerated.source_read_checked
#print axioms Parser.LALRGenerated.source_notation_checked
#print axioms Parser.LALRGenerated.lowering_checked
#print axioms Parser.LALRGenerated.ebnf_correct
#print axioms Parser.LALRGenerated.source_parse_correct
#print axioms Parser.LALRGenerated.located_fuel
#print axioms Parser.LALRGenerated.source_parseLocated_correct
#print axioms Parser.LALRGenerated.parseLocated_erases
#print axioms Parser.LALRGenerated.safety_checked
#print axioms Parser.LALRGenerated.execution_safe
#print axioms Parser.LALRGenerated.first_checked
#print axioms Parser.LALRGenerated.nullable_coverage
#print axioms Parser.LALRGenerated.lookahead_coverage
#print axioms Parser.LALRGenerated.items_checked
#print axioms Parser.LALRGenerated.accepts_iff_parse
#print axioms Parser.LALRGenerated.budget_checked
#print axioms Parser.LALRGenerated.progress_checked
#print axioms Parser.LALRGenerated.fuel_eq
#print axioms Parser.LALRGenerated.accepts_iff_parse_bounded
#print axioms Parser.LALRGenerated.parse_terminates
#print axioms Parser.LALRGenerated.parse_correct
#print axioms Parser.LALRGenerated.parsed_tree
LEAN
lake env lean "$task_tmp/Recursive.lean" > "$task_tmp/recursive-audit.txt"
bash scripts/audit-lean.sh "$task_tmp/recursive-audit.txt"

# The exact emitted table/edge constants participate in the certificate.
sed 's/some (.shift [0-9][0-9]*)/some (.shift 999)/' "$task_tmp/Recursive.lean" > "$task_tmp/BadShift.lean"
if lake env lean "$task_tmp/BadShift.lean" > "$task_tmp/bad-shift.log" 2>&1; then
  echo 'corrupted shift passed its structural certificate' >&2; exit 1
fi
# The partitioned proof exposes TableConditions after substituting its checked
# summaries. Require failure of the public safety root, not its old goal text.
rg -q 'safety_checked.*sorryAx' "$task_tmp/bad-shift.log"
sed 's/^def edges : List LALR.Edge := .*/def edges : List LALR.Edge := []/' \
  "$task_tmp/Recursive.lean" > "$task_tmp/MissingEdges.lean"
if lake env lean "$task_tmp/MissingEdges.lean" > "$task_tmp/missing-edges.log" 2>&1; then
  echo 'omitted transitions passed their structural certificate' >&2; exit 1
fi
rg -q 'safety_checked.*sorryAx' "$task_tmp/missing-edges.log"

# Facts are certified about the emitted grammar; stripping them cannot pass.
sed 's/^def firstFacts : Array LALR.First := .*/def firstFacts : Array LALR.First := #[]/' \
  "$task_tmp/Recursive.lean" > "$task_tmp/MissingFirst.lean"
if lake env lean "$task_tmp/MissingFirst.lean" > "$task_tmp/missing-first.log" 2>&1; then
  echo 'omitted nullable/FIRST facts passed their certificate' >&2; exit 1
fi
# cbv exposes the false certificate obligation before reporting its failure.
rg -q '^⊢ false = true$' "$task_tmp/missing-first.log"
rg -q 'first_checked.*sorryAx' "$task_tmp/missing-first.log"

# Completeness must depend on the actual item annotations, including the start.
sed 's/^noncomputable def itemStates : Array LALR.ItemSet := .*/noncomputable def itemStates : Array LALR.ItemSet := #[]/' \
  "$task_tmp/Recursive.lean" > "$task_tmp/MissingItems.lean"
if lake env lean "$task_tmp/MissingItems.lean" > "$task_tmp/missing-items.log" 2>&1; then
  echo 'omitted LR items passed their completeness certificate' >&2; exit 1
fi
rg -q 'items_checked.*sorryAx' "$task_tmp/missing-items.log"
rg -q 'accepts_iff_parse.*sorryAx' "$task_tmp/missing-items.log"

# The runtime coefficients must agree with the independently checked budget.
sed 's/^def fuel (input : List Nat) : Nat := .*/def fuel (input : List Nat) : Nat := 0/' \
  "$task_tmp/Recursive.lean" > "$task_tmp/BadFuel.lean"
if lake env lean "$task_tmp/BadFuel.lean" > "$task_tmp/bad-fuel.log" 2>&1; then
  echo 'changed runtime fuel passed its budget certificate' >&2; exit 1
fi
rg -q 'fuel_eq.*sorryAx' "$task_tmp/bad-fuel.log"
rg -q 'accepts_iff_parse_bounded.*sorryAx' "$task_tmp/bad-fuel.log"

# Keep table proofs intact while corrupting only the source-to-CFG witness.
# This must invalidate the composed source parser contract itself.
sed '/^noncomputable def loweringWitness /s/:= ⟨/:= ⟨#[Parser.EBNF.Expr.ref "missing"] ++/' \
  "$task_tmp/Recursive.lean" > "$task_tmp/BadLowering.lean"
if lake env lean "$task_tmp/BadLowering.lean" > "$task_tmp/bad-lowering.log" 2>&1; then
  echo 'corrupted EBNF meanings passed their lowering certificate' >&2; exit 1
fi
rg -q 'lowering_checked.*sorryAx' "$task_tmp/bad-lowering.log"
rg -q 'source_parse_correct.*sorryAx' "$task_tmp/bad-lowering.log"

# Independently read source text must agree with the certified EBNF tree.
sed 's/^def source : String := .*/def source : String := "s : unknown;"/' \
  "$task_tmp/Recursive.lean" > "$task_tmp/BadSource.lean"
if lake env lean "$task_tmp/BadSource.lean" > "$task_tmp/bad-source.log" 2>&1; then
  echo 'changed EBNF source passed its reader certificate' >&2; exit 1
fi
rg -q 'source_read_checked.*sorryAx' "$task_tmp/bad-source.log"
rg -q 'source_parse_correct.*sorryAx' "$task_tmp/bad-source.log"

# A conflict or undefined reference must not replace an existing output.
cp "$task_tmp/Recursive.lean" "$task_tmp/preserved.lean"
printf '%s\n' "s : s '+' s | 'id';" > "$task_tmp/conflict.ebnf"
if "$generator" --single "$task_tmp/conflict.ebnf" "$task_tmp/Recursive.lean" > "$task_tmp/conflict.log" 2>&1; then
  echo 'ambiguous grammar unexpectedly generated tables' >&2; exit 1
fi
rg -q 'LALR conflict in state' "$task_tmp/conflict.log"
cmp "$task_tmp/Recursive.lean" "$task_tmp/preserved.lean"
printf '%s\n' 's : undefined;' > "$task_tmp/undefined.ebnf"
if "$generator" --single "$task_tmp/undefined.ebnf" "$task_tmp/Recursive.lean" > "$task_tmp/undefined.log" 2>&1; then
  echo 'undefined grammar rule unexpectedly generated tables' >&2; exit 1
fi
rg -q 'undefined rule undefined' "$task_tmp/undefined.log"
cmp "$task_tmp/Recursive.lean" "$task_tmp/preserved.lean"
echo 'EBNF preservation and LALR safety/FIRST/completeness certificates, recursive execution, mutation and conflict checks passed'
