import RumocaCore.Array.Solve
import RumocaCore.Array.Semantics
import RumocaCore.Solve.PointwiseProofs

/-! The executable Solve edge of the array profile. The partial residual
solver has its own soundness theorems. The composed theorem covers derivative,
initialization and the actual dense Jacobian output generated by forward AD.
These mathematical Real results do not yet license production C or FMUs. -/
noncomputable section
namespace Rumoca.ArrayProfile
open Rumoca.Tensor Solve.Tensor

def environment (state input : Value α shape) : Env α [shape, shape] :=
  Env.push state (Env.push input Env.empty)

theorem square_coefficients_eval (ops : ScalarOps α) (zero one : α) (state input : Value α shape) :
    (squareJacobianProgram shape).coefficients.eval ops zero one (environment state input) =
      BinaryOp.jvp ops .mul input input (Value.fill shape one) (Value.fill shape one) := rfl

/-- The actual forward-generated coefficients materialize the square
Jacobian, with the two contributions of the shared input both present. -/
theorem square_jacobian_eval (state input : Value ℝ shape) :
    ((squareJacobianProgram shape).eval AD.realOps 0 1 (environment state input)).toMatrix =
      AD.squareJacobian (fun i => input[i]) := by
  simp only [DiagonalProgram.eval, Value.toMatrix_ofMatrix, square_coefficients_eval]
  ext i j
  simp [AD.squareJacobian, Matrix.diagonal, BinaryOp.jvp, BinaryOp.eval, BinaryOp.scalar, AD.realOps]

theorem JacobianOf.square_iff (input : AD.Space shape) (matrix : Jacobian shape) :
    JacobianOf (fun x => BinaryOp.denote AD.realOps .mul x x) input matrix ↔
      matrix = AD.squareJacobian input := by
  constructor
  · rintro ⟨derivative, hd, hm⟩
    have he := hd.unique (AD.square_hasFDerivAt input)
    apply Matrix.mulVec_injective
    funext tangent
    rw [hm, he, AD.square_jacobian_correct]
  · rintro rfl
    exact ⟨AD.squareDifferential input, AD.square_hasFDerivAt input, AD.square_jacobian_correct input⟩

theorem value_eq_iff (left right : Value α shape) :
    (∀ i : Fin shape.volume, left[i] = right[i]) ↔ left = right :=
  ⟨fun h => Value.ext (fun i hi => h ⟨i, hi⟩), fun h i => congrArg (fun v : Value α shape => v[i]) h⟩

/-- Soundness of the actual partial residual solver, for any tensor shape. -/
theorem DAE.solveResidual_correct (expr : Expr shape) (program : Program [shape, shape] shape)
    (checked : solveResidual? expr = some program) (state input derivative : Value ℝ shape) :
    (∀ i, expr.denote (fun j => state[j]) (fun j => input[j]) (fun j => derivative[j]) i = 0) ↔
      derivative = program.eval AD.realOps 0 1 (environment state input) := by
  unfold solveResidual? at checked
  split at checked
  · cases checked
    simpa [Expr.denote, Program.eval, environment, Env.push, sub_eq_zero] using value_eq_iff derivative input
  · cases checked
    have h := value_eq_iff derivative (BinaryOp.eval AD.realOps .mul input input)
    simpa [Expr.denote, squareProgram, Program.eval, environment, Env.push,
      BinaryOp.eval, BinaryOp.denote, sub_eq_zero] using h
  · cases checked

theorem DAE.solveInitial_correct (expr : Expr shape) (program : Program [] shape)
    (checked : solveInitial? expr = some program) (state input derivative : Value ℝ shape) :
    (∀ i, expr.denote (fun j => state[j]) (fun j => input[j]) (fun j => derivative[j]) i = 0) ↔
      state = program.eval AD.realOps 0 1 Env.empty := by
  unfold solveInitial? at checked
  split at checked
  · cases checked
    simpa [Expr.denote, fill, Program.eval, Literal.eval] using value_eq_iff state (Value.fill shape 0)
  · cases checked

theorem DAE.solveJacobian_correct (expr : Option (Expr shape))
    (program : Option (DiagonalProgram [shape, shape] shape)) (checked : solveJacobian? expr = some program)
    (state input derivative : Value ℝ shape) (matrix : Jacobian shape) :
    (match (generalizing := false) expr with
      | none => True
      | some e => JacobianOf (fun value => e.denote (fun j => state[j]) value (fun j => derivative[j]))
          (fun j => input[j]) matrix) ↔
    (match (generalizing := false) program with
      | none => True
      | some p => matrix = (p.eval AD.realOps 0 1 (environment state input)).toMatrix) := by
  unfold solveJacobian? at checked
  split at checked
  · cases checked; rfl
  · cases checked
    simp only [Expr.denote, square_jacobian_eval]
    exact JacobianOf.square_iff _ _
  · cases checked

/-- Both equation components are preserved by a successful candidate: the
solved derivative and the dense matrix observation from the same DAE. -/
theorem Solved.lower?_correct (dae : DAE.Model source) (kernel : Solve.PointwiseIVP stateShape)
    (checked : lower? dae = some kernel) (state input derivative : Value ℝ stateShape)
    (matrix : Jacobian stateShape) :
    dae.Equation (fun i => state[i]) (fun i => input[i]) (fun i => derivative[i]) matrix ↔
      kernel.Equation state input derivative matrix := by
  obtain ⟨rhs, initial, diagonal, hr, _, hj, rfl⟩ := lower_fields dae kernel checked
  cases he : dae.jacobian <;> cases diagonal <;>
    simpa only [DAE.Model.Equation, Solve.PointwiseIVP.Equation, Solve.PointwiseIVP.problem,
      Solve.IVP.rhs, Solve.IVP.environment, environment, he] using
      and_congr (DAE.solveResidual_correct _ _ hr state input derivative)
        (DAE.solveJacobian_correct _ _ hj state input derivative matrix)

theorem Solved.lower?_initial (dae : DAE.Model source) (kernel : Solve.PointwiseIVP stateShape)
    (checked : lower? dae = some kernel) (state input derivative : Value ℝ stateShape) :
    dae.Initial (fun i => state[i]) (fun i => input[i]) (fun i => derivative[i]) ↔ kernel.Initial state := by
  obtain ⟨rhs, initial, diagonal, _, hi, _, rfl⟩ := lower_fields dae kernel checked
  exact DAE.solveInitial_correct _ _ hi state input derivative

theorem Solved.lower_correct (dae : DAE.Model source) (state input derivative : Value ℝ stateShape)
    (matrix : Jacobian stateShape) :
    dae.Equation (fun i => state[i]) (fun i => input[i]) (fun i => derivative[i]) matrix ↔
      (lower dae).Equation state input derivative matrix :=
  lower?_correct dae _ (lower_checked dae) state input derivative matrix

theorem Solved.lower_initial (dae : DAE.Model source) (state input derivative : Value ℝ stateShape) :
    dae.Initial (fun i => state[i]) (fun i => input[i]) (fun i => derivative[i]) ↔ (lower dae).Initial state :=
  lower?_initial dae _ (lower_checked dae) state input derivative

/-- The complete named source equation, including `jacobian(...)`, is
equivalent to execution of the prepared tensor IVP and its matrix observation. -/
theorem lowering_chain_correct (m : Model) (resolved : m.Resolved)
    (values derivatives : String → Value ℝ stateShape) (matrices : String → Jacobian stateShape) :
    m.Equation (fun name i => (values name)[i]) (fun name i => (derivatives name)[i]) matrices ↔
      (Solved.lower (DAE.lower (Flat.lower m resolved))).Equation
        (values m.header.state) (values m.header.input) (derivatives m.header.state) (m.jacobianValue matrices) :=
  (dae_chain_correct m resolved _ _ matrices).trans (Solved.lower_correct _ _ _ _ _)

theorem initialization_chain_correct (m : Model) (resolved : m.Resolved)
    (values : String → Value ℝ stateShape) :
    m.Initial (fun name i => (values name)[i]) ↔
      (Solved.lower (DAE.lower (Flat.lower m resolved))).Initial (values m.header.state) :=
  (dae_initialization_correct m resolved (fun name i => (values name)[i])
    (fun name i => (values name)[i])).trans (Solved.lower_initial _ _ _ _)

end Rumoca.ArrayProfile
