import Parser.LALR.Generator
import Parser.LALR.EBNF
import Parser.LALR.Safety

/-! Experimental table emitter. All implementation is Lean and lives in the
parser package. It does not publish a `CertifiedParser`: the general EBNF and
table completeness proofs must be finished before production can use it. -/
open Parser.LALR

namespace LALRGenerator

private def array (xs : Array String) : String :=
  "#[" ++ String.intercalate ", " xs.toList ++ "]"

private def atom : Atom → String
  | .terminal t => s!".terminal {t}"
  | .nonterminal n => s!".nonterminal {n}"

private def production (p : Production) : String :=
  s!"⟨{p.input}, [" ++ String.intercalate ", " (p.output.map atom) ++ "]⟩"

private def action : Option Action → String
  | none => "none"
  | some (.shift n) => s!"some (.shift {n})"
  | some (.reduce n) => s!"some (.reduce {n})"
  | some .accept => "some .accept"

private def edge (e : Edge) : String := s!"⟨{e.source}, {atom e.symbol}, {e.target}⟩"

private def firstFact (f : First) : String :=
  s!"⟨{f.nullable}, [" ++ String.intercalate ", " (f.terminals.map toString) ++ "]⟩"

def emit (source : String) (moduleNamespace : String := "Parser.LALRGenerated") : Except String String := do
  if !(moduleNamespace.splitOn ".").all (fun part =>
      !part.isEmpty && part.toList.all (fun c => Parser.identRest c) &&
        (part.toList.head?).any Parser.identStart) then
    throw "invalid generated namespace"
  let p ← Frontend.compile source
  let c ← generate p.grammar
  let g := p.grammar
  let facts ← firstSets g
  if !FirstCheck.validate g facts then
    throw "candidate failed nullable/FIRST validation"
  if !Safety.validate g c.tables c.collection.edges.toList then
    throw "candidate failed structural safety validation"
  return "-- Experimental LALR(1) candidate tables. Not a production certificate.\n" ++
    "-- Generated by the in-tree Lean lalrgen; do not edit.\n" ++
    s!"-- {c.canonicalStates} canonical states; {c.collection.states.size} LALR states.\n" ++
    "import Parser.LALR.SafetyProofs\nimport Parser.LALR.FirstProofs\n" ++
    "import Parser.Token\nimport Parser.LALR.Located\n\nopen Parser\n\n" ++
    s!"namespace {moduleNamespace}\n\n" ++
    s!"def source : String := {repr source}\n\n" ++
    s!"def alphabet : Array Parser.Symbol := {repr p.alphabet}\n\n" ++
    s!"def grammar : LALR.Grammar := ⟨{g.terminals}, {g.nonterminals}, {g.start}, " ++
    array (g.productions.map production) ++ "⟩\n\n" ++
    "def tables : LALR.Tables := ⟨" ++ array (c.tables.actions.map fun row => array (row.map action)) ++
    ", " ++ array (c.tables.gotos.map fun row => array (row.map fun n =>
      n.map (fun n => s!"some {n}") |>.getD "none")) ++ "⟩\n\n" ++
    "def edges : List LALR.Edge := [" ++
      String.intercalate ", " (c.collection.edges.toList.map edge) ++ "]\n\n" ++
    "def firstFacts : Array LALR.First := " ++ array (facts.map firstFact) ++ "\n\n" ++
    "-- Proof-producing normalization; all resulting terms are kernel checked.\n" ++
    "set_option maxRecDepth 10000 in\nset_option maxHeartbeats 8000000 in\n" ++
    "set_option cbv.warning false in\n" ++
    "theorem first_checked : LALR.FirstCheck.validate grammar firstFacts = true := by cbv\n\n" ++
    "theorem nullable_coverage (symbols : List LALR.Atom)\n" ++
    "    (h : grammar.semantics.Derives symbols []) :\n" ++
    "    (LALR.firstSequence firstFacts symbols).nullable = true :=\n" ++
    "  LALR.FirstProofs.nullable_complete first_checked h\n\n" ++
    "theorem lookahead_coverage (symbols : List LALR.Atom) (word : List Nat) (following : Nat)\n" ++
    "    (h : grammar.semantics.Derives symbols (word.map _root_.Symbol.terminal)) :\n" ++
    "    word.headD following ∈ LALR.lookaheads firstFacts symbols following :=\n" ++
    "  LALR.FirstProofs.lookahead_complete first_checked h\n\n" ++
    "-- Structural safety only; completeness, frontend correctness and progress remain open.\n" ++
    "set_option maxRecDepth 10000 in\nset_option maxHeartbeats 8000000 in\n" ++
    "theorem safety_checked : LALR.Safety.validate grammar tables edges = true := by decide +kernel\n\n" ++
    "theorem execution_safe (fuel : Nat) (input : List Nat) (error : LALR.Failure)\n" ++
    "    (h : LALR.parse grammar tables fuel input = .error error) :\n" ++
    "    error = .exhausted ∨ error = .rejected :=\n" ++
    "  LALR.Safety.validated_parse_safe safety_checked h\n\n" ++
    "-- Every grammar gets the same automatic production/terminal span API.\n" ++
    "def parseLocated (source : String) (fuel : Nat)\n" ++
    "    (tokens : List (Parser.Source.Located source Token)) :=\n" ++
    "  LALR.parseLocated grammar tables fuel (tokens.map fun t =>\n" ++
    "    ⟨(alphabet.findIdx? (· == t.value.symbol)).getD (alphabet.size + 1), t.span⟩)\n\n" ++
    s!"end {moduleNamespace}\n"

end LALRGenerator

def main (args : List String) : IO UInt32 := do
  let (moduleNamespace, args) := match args with
    | "--namespace" :: ns :: rest => (ns, rest)
    | _ => ("Parser.LALRGenerated", args)
  match args with
  | [input, output] =>
    try
      let source ← IO.FS.readFile input
      match LALRGenerator.emit source moduleNamespace with
      | .error error => IO.eprintln error; return (1 : UInt32)
      | .ok text => IO.FS.writeFile output text; return (0 : UInt32)
    catch e => IO.eprintln (toString e); return (1 : UInt32)
  | _ =>
    IO.eprintln "usage: lalrgen [--namespace Name] grammar.ebnf Candidate.lean (experimental; no production certificate)"
    return (2 : UInt32)
