import RumocaEFMI.TensorAlgorithmProofs
import ProofAudit.Audit
#audit axioms Rumoca.EFMI.squareKernel
#audit axioms Rumoca.EFMI.squareExtent
#audit axioms Rumoca.EFMI.renderTensorAlgorithm
#audit axioms Rumoca.EFMI.admittedModel
#audit axioms Rumoca.EFMI.tensorAlgorithmSource
#audit axioms Rumoca.EFMI.TensorAlgorithm.SourceExec
#audit axioms Rumoca.EFMI.TensorAlgorithm.SourceRuns
#audit axioms Rumoca.EFMI.TensorAlgorithm.StartupSemantics
#audit axioms Rumoca.EFMI.TensorAlgorithm.RecalibrateSemantics
#audit axioms Rumoca.EFMI.TensorAlgorithm.StepSemantics
#audit axioms Rumoca.EFMI.TensorAlgorithm.ADSemantics
#audit axioms Rumoca.EFMI.TensorAlgorithm.Interfaced
#audit axioms Rumoca.EFMI.TensorAlgorithm.interfaced
#audit axioms Rumoca.EFMI.TensorAlgorithm.SourceContract
#audit axioms Rumoca.EFMI.TensorAlgorithm.source_contract
#audit axioms Rumoca.EFMI.TensorAlgorithm.prepared
#audit axioms Rumoca.EFMI.TensorAlgorithm.square.lexed
#audit axioms Rumoca.EFMI.TensorAlgorithm.square.checked
#audit axioms Rumoca.EFMI.TensorAlgorithm.square.structure_built
#audit axioms Rumoca.EFMI.TensorAlgorithm.square.denotes
#audit axioms Rumoca.EFMI.TensorAlgorithm.square.witness
#audit axioms Rumoca.EFMI.TensorAlgorithm.square.parsed
#audit axioms Rumoca.EFMI.TensorAlgorithm.square_ast
#audit axioms Rumoca.EFMI.TensorAlgorithm.emitted_parses
#audit axioms Rumoca.EFMI.TensorAlgorithm.emitted_prepared
#audit axioms Rumoca.EFMI.TensorAlgorithm.AlgorithmContract
#audit axioms Rumoca.EFMI.TensorAlgorithm.algorithm_correct
#audit axioms Rumoca.EFMI.TensorAlgorithm.outputCells
#audit axioms Rumoca.EFMI.TensorAlgorithm.run
#audit axioms Rumoca.EFMI.TensorAlgorithm.observe
#audit axioms Rumoca.EFMI.TensorAlgorithm.step_lowered
#audit axioms Rumoca.EFMI.TensorAlgorithm.withDoStep
#audit axioms Rumoca.EFMI.TensorAlgorithm.preflightWith
#audit axioms Rumoca.EFMI.TensorAlgorithm.checkWith
#audit axioms Rumoca.EFMI.TensorAlgorithm.reraise
#audit axioms Rumoca.EFMI.TensorAlgorithm.unsignaledGuard
#audit axioms Rumoca.EFMI.TensorAlgorithm.coefficientBody
#audit axioms Rumoca.EFMI.TensorAlgorithm.unclearedBody
#audit axioms Rumoca.EFMI.TensorAlgorithm.productUncheckedBody
#audit axioms Rumoca.EFMI.TensorAlgorithm.sumUncheckedBody
#audit axioms Rumoca.EFMI.TensorAlgorithm.argumentBody
#audit axioms Rumoca.EFMI.TensorAlgorithm.writesFirstBody
#audit axioms Rumoca.EFMI.TensorAlgorithm.changed_rejected
#audit axioms Rumoca.EFMI.TensorAlgorithm.coefficient_rejected
#audit axioms Rumoca.EFMI.TensorAlgorithm.uncleared_rejected
#audit axioms Rumoca.EFMI.TensorAlgorithm.product_unchecked_rejected
#audit axioms Rumoca.EFMI.TensorAlgorithm.sum_unchecked_rejected
#audit axioms Rumoca.EFMI.TensorAlgorithm.argument_rejected
#audit axioms Rumoca.EFMI.TensorAlgorithm.writes_first_rejected
#audit axioms Rumoca.EFMI.TensorAlgorithm.changed_bodies_prepare
#audit axioms Rumoca.EFMI.TensorAlgorithm.unsignaledBody
#audit axioms Rumoca.EFMI.TensorAlgorithm.unraisedBody
#audit axioms Rumoca.EFMI.TensorAlgorithm.checkFormBody
#audit axioms Rumoca.EFMI.TensorAlgorithm.rejectedChecks
#audit axioms Rumoca.EFMI.TensorAlgorithm.signals_rejected
