import Tests.Audit.TensorArtifact
import Tests.Audit.TensorEFMIExecutedContract
import Tests.Audit.TensorEFMIFiniteJacobian
import Tests.Audit.TensorEFMISourceJacobian
import Tests.Audit.TensorEFMISourceMethod
import Tests.Audit.TensorEFMISourceObservation
-- Aggregator for the per-source-module axiom audits of the compiler.
-- Each imported module audits exactly the roots of one Rumoca.* source
-- module, so Lake elaborates them as independent parallel jobs while this
-- aggregator keeps the RumocaCompilerChecks library root name unchanged.
import Tests.Audit.ArrayCompiler
import Tests.Audit.ArrayProofs
import Tests.Audit.Behavioral
import Tests.Audit.Compiler
import Tests.Audit.ConstantAdapterChars
import Tests.Audit.ConstantCompiler
import Tests.Audit.ConstantProduction
import Tests.Audit.ConstantProofs
import Tests.Audit.EFMITensorArchiveProofs
import Tests.Audit.FMI3AbsentVariableProofs
import Tests.Audit.FMI3AdapterProofs
import Tests.Audit.FMI3BuildProofs
import Tests.Audit.FMI3CapabilityProofs
import Tests.Audit.FMI3CountProofs
import Tests.Audit.FMI3CreatedInitializationAccess
import Tests.Audit.FMI3CreatedInitializationProtocol
import Tests.Audit.FMI3CSHistory
import Tests.Audit.FMI3CSInitialization
import Tests.Audit.FMI3CSLifecycle
import Tests.Audit.FMI3CSLoggedLifecycle
import Tests.Audit.FMI3CSMixedRecords
import Tests.Audit.FMI3CSMixedRun
import Tests.Audit.FMI3CSProtocol
import Tests.Audit.FMI3CSProtocolPrefixes
import Tests.Audit.FMI3CSProtocolRuntime
import Tests.Audit.FMI3CSRelease
import Tests.Audit.FMI3CSRun
import Tests.Audit.FMI3CSRunLifecycle
import Tests.Audit.FMI3CSRunLogging
import Tests.Audit.FMI3CSRunRecords
import Tests.Audit.FMI3DebugLoggingProofs
import Tests.Audit.FMI3DerivativeProofs
import Tests.Audit.FMI3DiscreteEvaluationProofs
import Tests.Audit.FMI3EventIndicatorProofs
import Tests.Audit.FMI3FactoryAdmission
import Tests.Audit.FMI3FactoryValidation
import Tests.Audit.FMI3Float64Environment
import Tests.Audit.FMI3Float64Proofs
import Tests.Audit.FMI3Float64Rejection
import Tests.Audit.FMI3Float64SetEnvironment
import Tests.Audit.FMI3Float64SetProofs
import Tests.Audit.FMI3IdentitySource
import Tests.Audit.FMI3InitializationAccess
import Tests.Audit.FMI3InitializationCalls
import Tests.Audit.FMI3InitializationCSRun
import Tests.Audit.FMI3InitializationMERun
import Tests.Audit.FMI3InitializationProofs
import Tests.Audit.FMI3InitializationProtocol
import Tests.Audit.FMI3InitializationProtocolCS
import Tests.Audit.FMI3InitializationProtocolME
import Tests.Audit.FMI3InitializationProtocolPrefixes
import Tests.Audit.FMI3InitializationRestart
import Tests.Audit.FMI3InitializationSemantics
import Tests.Audit.FMI3LiteralProofs
import Tests.Audit.FMI3LoggingProofs
import Tests.Audit.FMI3MEEnvironment
import Tests.Audit.FMI3MEFailureRecovery
import Tests.Audit.FMI3MEHistory
import Tests.Audit.FMI3MEInitialization
import Tests.Audit.FMI3MELifecycle
import Tests.Audit.FMI3MEMixedLifecycle
import Tests.Audit.FMI3MEMixedRun
import Tests.Audit.FMI3MENumericalEnvironment
import Tests.Audit.FMI3MENumericalHistory
import Tests.Audit.FMI3MENumericalLifecycle
import Tests.Audit.FMI3MENumericalRunLifecycle
import Tests.Audit.FMI3MENumericalRunObservations
import Tests.Audit.FMI3MEProtocol
import Tests.Audit.FMI3MEProtocolPrefixes
import Tests.Audit.FMI3MEProtocolRuntime
import Tests.Audit.FMI3MERelease
import Tests.Audit.FMI3ModelAdvance
import Tests.Audit.FMI3NameProofs
import Tests.Audit.FMI3NominalProofs
import Tests.Audit.FMI3PublicContracts
import Tests.Audit.FMI3Recovery
import Tests.Audit.FMI3ResetProofs
import Tests.Audit.FMI3Restart
import Tests.Audit.FMI3RuntimeEnvironment
import Tests.Audit.FMI3SimulationRestart
import Tests.Audit.FMI3StateEnvironment
import Tests.Audit.FMI3StateProofs
import Tests.Audit.FMI3StaticCreation
import Tests.Audit.FMI3StaticInitialization
import Tests.Audit.FMI3StaticInitializationErrors
import Tests.Audit.FMI3StaticLifecycle
import Tests.Audit.FMI3StaticLogging
import Tests.Audit.FMI3StaticRejection
import Tests.Audit.FMI3StaticReset
import Tests.Audit.FMI3StepProofs
import Tests.Audit.FMI3TerminationProofs
import Tests.Audit.FMI3TerminationRelease
import Tests.Audit.FMI3TimeProofs
import Tests.Audit.FMI3VersionProofs
import Tests.Audit.Initialization
import Tests.Audit.InitializationDiagnosticProofs
import Tests.Audit.Lowering
import Tests.Audit.ParseFilesProofs
import Tests.Audit.Provenance
import Tests.Audit.Semantics
import Tests.Audit.Source
import Tests.Audit.TensorAdapterChars
import Tests.Audit.TensorProduction
import Tests.Audit.Verified
