-- Aggregator for the per-source-module axiom audits (FMI3SourceCallPolicyAudit).
-- Each imported module audits exactly the roots of one source module,
-- so Lake elaborates them as independent parallel jobs while this
-- aggregator keeps its check-library root name unchanged.
import Tests.FMI3SourceCallPolicyAudit.Rumoca_FMI3AtomicCalls
import Tests.FMI3SourceCallPolicyAudit.Rumoca_FMI3AtomicFlagFrame
import Tests.FMI3SourceCallPolicyAudit.Rumoca_FMI3AtomicOperations
import Tests.FMI3SourceCallPolicyAudit.RumocaFMI3_CallPolicy
import Tests.FMI3SourceCallPolicyAudit.Rumoca_FMI3CallPolicy
import Tests.FMI3SourceCallPolicyAudit.Rumoca_FMI3ConcurrentSlots
import Tests.FMI3SourceCallPolicyAudit.Rumoca_FMI3ControlledInitialization
import Tests.FMI3SourceCallPolicyAudit.Rumoca_FMI3FactoryClaims
import Tests.FMI3SourceCallPolicyAudit.Rumoca_FMI3FactorySuffix
import Tests.FMI3SourceCallPolicyAudit.Rumoca_FMI3HostCalls
import Tests.FMI3SourceCallPolicyAudit.Rumoca_FMI3InitializationHistories
import Tests.FMI3SourceCallPolicyAudit.Rumoca_FMI3InitialRecorded
import Tests.FMI3SourceCallPolicyAudit.Rumoca_FMI3InstanceAuthority
import Tests.FMI3SourceCallPolicyAudit.Rumoca_FMI3PublicationHistories
import Tests.FMI3SourceCallPolicyAudit.Rumoca_FMI3ReleaseBounds
import Tests.FMI3SourceCallPolicyAudit.Rumoca_FMI3ReservationBounds
import Tests.FMI3SourceCallPolicyAudit.Rumoca_FMI3ReservationHistories
import Tests.FMI3SourceCallPolicyAudit.Rumoca_FMI3ReservationOrigins
import Tests.FMI3SourceCallPolicyAudit.Rumoca_FMI3ResourceHistories
import Tests.FMI3SourceCallPolicyAudit.Rumoca_FMI3RetainedInitialization
import Tests.FMI3SourceCallPolicyAudit.Rumoca_FMI3RuntimeLinkage
import Tests.FMI3SourceCallPolicyAudit.Rumoca_FMI3RuntimeStorage
import Tests.FMI3SourceCallPolicyAudit.Rumoca_FMI3ScanClaims
import Tests.FMI3SourceCallPolicyAudit.Rumoca_FMI3StateSetterPolicy
import Tests.FMI3SourceCallPolicyAudit.Rumoca_FMI3StaticInitializationHistories
import Tests.FMI3SourceCallPolicyAudit.Rumoca_FMI3SubcallDomains
