-- LALR(1) tables with checked token-language and execution contracts.
-- Generated by the in-tree Lean lalrgen; do not edit.
-- 268 canonical states; 222 LALR states.
-- Certificates are split across the Generated/ directory; this umbrella
-- imports them and states the final theorems.
import ModelicaParser.Generated.Tables
import ModelicaParser.Generated.Source
import ModelicaParser.Generated.Items
import ModelicaParser.Generated.Reductions0
import ModelicaParser.Generated.Reductions1
import ModelicaParser.Generated.Reductions2
import ModelicaParser.Generated.Reductions3
import ModelicaParser.Generated.Reductions4
import ModelicaParser.Generated.Safety
import ModelicaParser.Generated.Progress

open Parser

namespace Rumoca.Generated

set_option maxRecDepth 100000
set_option maxHeartbeats 8000000

theorem accepts_iff_parse (word : List Nat) :
    grammar.Accepts word ↔ ∃ fuel tree, LALR.parse grammar tables fuel word = .ok tree :=
  LALR.Completeness.accepts_iff_parse items_checked

theorem nullable_coverage (symbols : List LALR.Atom)
    (h : grammar.semantics.Derives symbols []) :
    (LALR.firstSequence firstFacts symbols).nullable = true :=
  LALR.FirstProofs.nullable_complete first_checked h

theorem lookahead_coverage (symbols : List LALR.Atom) (word : List Nat) (following : Nat)
    (h : grammar.semantics.Derives symbols (word.map _root_.Symbol.terminal)) :
    word.headD following ∈ LALR.lookaheads firstFacts symbols following :=
  LALR.FirstProofs.lookahead_complete first_checked h

def fuelForLength (count : Nat) : Nat := 16 * count + 15 + 1

def fuel (input : List Nat) : Nat := fuelForLength input.length

theorem fuel_eq (input : List Nat) :
    fuel input = LALR.Progress.bound fuelBudget progressCredits input := by rfl

theorem accepts_iff_parse_bounded (word : List Nat) :
    grammar.Accepts word ↔ ∃ tree, LALR.parse grammar tables (fuel word) word = .ok tree := by
  rw [fuel_eq]
  exact LALR.Progress.accepts_iff_parse items_checked budget_checked safety_checked progress_checked word

theorem parse_terminates (word : List Nat) :
    (∃ tree, LALR.parse grammar tables (fuel word) word = .ok tree) ∨
      LALR.parse grammar tables (fuel word) word = .error .rejected := by
  rw [fuel_eq]
  exact LALR.Progress.parse_terminates budget_checked safety_checked progress_checked word

def parse (input : List Nat) : Except LALR.Failure LALR.Tree :=
  LALR.parse grammar tables (fuel input) input

theorem parse_correct (word : List Nat) :
    (grammar.Accepts word ↔ ∃ tree, parse word = .ok tree) ∧
    ((∃ tree, parse word = .ok tree) ∨ parse word = .error .rejected) :=
  ⟨accepts_iff_parse_bounded word, parse_terminates word⟩

theorem parsed_tree (word : List Nat) (tree : LALR.Tree) (parsed : parse word = .ok tree) :
    LALR.checkTree grammar word tree = true :=
  LALR.RuntimeProofs.run_checked (LALR.RuntimeProofs.initial grammar word)
    (by simpa only [parse, LALR.parse_eq_run] using parsed)

def parseSymbols (word : List Parser.Symbol) : Except LALR.Failure LALR.Tree :=
  parse (word.map encode)

theorem source_parse_correct (word : List Parser.Symbol) :
    Parser.EBNF.Metalanguage.Denotes source sourceGrammar ∧
    (Parser.EBNF.Accepts sourceGrammar word ↔ ∃ tree, parseSymbols word = .ok tree) ∧
    ((∃ tree, parseSymbols word = .ok tree) ∨ parseSymbols word = .error .rejected) :=
  ⟨source_notation_checked, (ebnf_correct word).trans (parse_correct (word.map encode)).1,
    (parse_correct (word.map encode)).2⟩

def tokenParser : LALR.TokenParser Parser.Symbol where
  grammar := grammar
  encode := encode
  run := parseSymbols
  accepts_iff word := (parse_correct (word.map encode)).1
  checked word tree parsed := parsed_tree (word.map encode) tree parsed
  terminates word := (parse_correct (word.map encode)).2

theorem execution_safe (fuel : Nat) (input : List Nat) (error : LALR.Failure)
    (h : LALR.parse grammar tables fuel input = .error error) :
    error = .exhausted ∨ error = .rejected :=
  LALR.Safety.validated_parse_safe safety_checked h

-- Every grammar gets the same bounded production/terminal span API.
def encodeLocatedTokens {text : String} (tokens : List (Source.Located text Token)) :
    List (Source.Located text Nat) :=
  tokens.map fun token => ⟨encode token.value.symbol, token.span⟩

def parseLocated (text : String) (tokens : List (Source.Located text Token)) :=
  LALR.parseLocated grammar tables (fuelForLength tokens.length) (encodeLocatedTokens tokens)

theorem located_fuel {text : String} (tokens : List (Source.Located text Token)) :
    fuelForLength tokens.length =
      LALR.Progress.bound fuelBudget progressCredits ((encodeLocatedTokens tokens).map (·.value)) := by
  simpa only [fuel, encodeLocatedTokens, List.length_map] using
    fuel_eq ((encodeLocatedTokens tokens).map (·.value))

theorem source_parseLocated_correct (text : String) (tokens : List (Source.Located text Token)) :
    Parser.EBNF.Metalanguage.Denotes source sourceGrammar ∧
    (Parser.EBNF.Accepts sourceGrammar (tokens.map (fun token => token.value.symbol)) ↔
      ∃ result, parseLocated text tokens = .ok result) ∧
    ((∃ result, parseLocated text tokens = .ok result) ∨
      parseLocated text tokens = .error .rejected) := by
  have checked := LALR.parseLocated_correct items_checked budget_checked safety_checked
    progress_checked (encodeLocatedTokens tokens)
  rw [← located_fuel tokens] at checked
  refine ⟨source_notation_checked, ?_, checked.2⟩
  exact (ebnf_correct (tokens.map (fun token => token.value.symbol))).trans
    (by simpa only [encodeLocatedTokens, List.map_map, Function.comp_def, parseLocated]
      using checked.1)

theorem parseLocated_erases (text : String) (tokens : List (Source.Located text Token)) :
    (parseLocated text tokens).map (·.tree) =
      parseSymbols (tokens.map (fun token => token.value.symbol)) := by
  have erased := LALR.parseLocated_erases grammar tables
    (fuelForLength tokens.length) (encodeLocatedTokens tokens)
  simpa only [parseLocated, parseSymbols, parse, fuel,
    encodeLocatedTokens, List.map_map, List.length_map, Function.comp_def] using erased

end Rumoca.Generated
