import RumocaCore.IR

/-! Typed shape of the binary64 C backend. `eval` is parameterized by the
interpretation of one and addition: Lowering.lean proves the ideal interpretation;
Execution.lean and RumocaCore.Real.Binary64 specify and prove finite execution
and rounding. Native Float is not assumed correct. -/
namespace Rumoca.C

inductive Expr where
  | one
  | arg
  | add (left right : Expr)
  deriving Repr, BEq, DecidableEq

def eval [OfNat α 1] [Add α] (x : α) : Expr → α
  | .one => 1
  | .arg => x
  | .add a b => eval x a + eval x b

def compileProgram (p : Solve.Program n) (registers : Fin n → Expr) : Expr :=
  match p with
  | .ret r => registers r
  | .one next => compileProgram next
      (fun i => if h : i.val < n then registers ⟨i.val, h⟩ else .one)

theorem compileProgram_correct [OfNat α 1] [Add α]
    (p : Solve.Program n) (registers : Fin n → Expr) (x : α) :
    eval x (compileProgram p registers) = Solve.evalWith (1 : α) p (fun i => eval x (registers i)) := by
  induction p with
  | ret r => rfl
  | @one n next ih =>
    simp only [compileProgram, Solve.evalWith, ih]
    congr 1
    funext i
    split <;> rfl

/-- All expressions in this backend have C type double. The loop counter is
separate control data and retains uint64_t; it is not a Modelica state. -/
structure Module where
  rhs : Expr
  deriving Repr, BEq, DecidableEq

def lower (m : Solve.Model source) : Module :=
  ⟨compileProgram m.derivative Fin.elim0⟩

def Module.step (m : Module) : Expr := .add .arg m.rhs

theorem rhs_correct [OfNat α 1] [Add α] (m : Solve.Model source) (x : α) :
    eval x (lower m).rhs = 1 := by
  simp [lower, m.derivative_source, Solve.unitDerivative, compileProgram, eval]

theorem step_correct [OfNat α 1] [Add α] (m : Solve.Model source) (x : α) :
    eval x (lower m).step = x + 1 := by
  simp [Module.step, eval, rhs_correct]

/-- Iteration uses the chosen numerical addition, without reassociation. -/
def run [OfNat α 1] [Add α] (m : Module) (x : α) : Nat → α
  | 0 => x
  | n + 1 => run m (eval x m.step) n

inductive SampleExec [OfNat α 1] [Add α] (m : Module) : α → Nat → α → Prop where
  | done (x) : SampleExec m x 0 x
  | more (x n out) : SampleExec m (eval x m.step) n out → SampleExec m x (n + 1) out

theorem sample_correct [OfNat α 1] [Add α] (m : Module) (x : α) (n : Nat) :
    SampleExec m x n (run m x n) := by
  induction n generalizing x with
  | zero => exact .done x
  | succ n ih => exact .more x n _ (ih _)

theorem sample_deterministic [OfNat α 1] [Add α]
    (h₁ : SampleExec m x n a) (h₂ : SampleExec m x n b) : a = b := by
  induction h₁ with
  | done => cases h₂; rfl
  | more _ _ _ _ ih => cases h₂ with | more _ _ _ h => exact ih h

def renderExpr : Expr → String
  | .one => "1.0"
  | .arg => "x"
  | .add a b => "(" ++ renderExpr a ++ " + " ++ renderExpr b ++ ")"

def preamble : String :=
  "/* Generated by lean_rumoca. Modelica Real: IEEE 754 binary64. */\n" ++
  "#include <stdint.h>\n#include <float.h>\n" ++
  "#if FLT_RADIX != 2 || DBL_MANT_DIG != 53 || DBL_MAX_EXP != 1024 || DBL_MIN_EXP != -1021 || FLT_EVAL_METHOD != 0\n" ++
  "#error \"Modelica Real backend requires IEEE 754 binary64 double\"\n#endif\n\n"

def render (m : Module) : String :=
  preamble ++
  "double rumoca_rhs(void) {\n  return " ++ renderExpr m.rhs ++ ";\n}\n\n" ++
  "double rumoca_step(double x) {\n  return " ++ renderExpr m.step ++ ";\n}\n\n" ++
  "double rumoca_sample(double x, uint64_t n) {\n" ++
  "  while (n != 0) {\n    x = " ++ renderExpr m.step ++ ";\n" ++
  "    n = n - UINT64_C(1);\n  }\n  return x;\n}\n"

/-- Byte layout only; CSyntax specifies its grammar and CExecution specifies execution. -/
def unitText : String := preamble ++
  "double rumoca_rhs(void) {\n  return 1.0;\n}\n\ndouble rumoca_step(double x) {\n  return (x + 1.0);\n}\n\ndouble rumoca_sample(double x, uint64_t n) {\n  while (n != 0) {\n    x = (x + 1.0);\n    n = n - UINT64_C(1);\n  }\n  return x;\n}\n"

def unitModule : Module := ⟨.one⟩

theorem lower_is_unit (m : Solve.Model source) : lower m = unitModule := by
  simp [lower, m.derivative_source, Solve.unitDerivative, compileProgram, unitModule]

set_option maxRecDepth 10000 in
theorem render_unit : render unitModule = unitText := by decide +kernel

theorem emission_is_unit (m : Solve.Model source) : render (lower m) = unitText := by
  rw [lower_is_unit, render_unit]

end Rumoca.C
