import RumocaC.StringLiteral

/-! A conservative envelope for ordinary quoted-token boundaries. Every
backslash protects the following character; all other characters except an
unescaped quote are allowed. This deliberately admits bodies that are not
valid C literals. Proving uniqueness against this larger language avoids
assuming that competing token spellings were generated by our own printer.
Escape values, newlines, encodings and adjacent-literal concatenation retain
their separate contracts. -/
namespace Rumoca.CString

inductive QuoteBody : List Char → Prop where
  | nil : QuoteBody []
  | plain : c ≠ '"' → c ≠ '\\' → QuoteBody rest → QuoteBody (c :: rest)
  | escape : QuoteBody rest → QuoteBody ('\\' :: c :: rest)

theorem QuoteBody.append (first : QuoteBody a) (second : QuoteBody b) : QuoteBody (a ++ b) := by
  induction first with
  | nil => exact second
  | plain quote slash body ih => exact .plain quote slash ih
  | escape body ih => exact .escape ih

theorem QuoteBody.boundary_unique (first : QuoteBody a) (second : QuoteBody b)
    (same : a ++ '"' :: restA = b ++ '"' :: restB) : a = b ∧ restA = restB := by
  induction first generalizing b restA restB with
  | nil =>
      cases second with
      | nil => exact ⟨rfl, (List.cons.inj same).2⟩
      | plain quote slash body => exact False.elim (quote (List.cons.inj same).1.symm)
      | escape body => simp at same
  | @plain c tail quote slash body ih =>
      cases second with
      | nil => exact False.elim (quote (List.cons.inj same).1)
      | @plain d tailB quoteB slashB bodyB =>
          have chars := List.cons.inj same
          obtain ⟨tails, rests⟩ := ih bodyB chars.2
          exact ⟨by rw [chars.1, tails], rests⟩
      | escape bodyB => exact False.elim (slash (List.cons.inj same).1)
  | @escape tail c body ih =>
      cases second with
      | nil => simp at same
      | plain quoteB slashB bodyB => exact False.elim (slashB (List.cons.inj same).1.symm)
      | @escape tailB d bodyB =>
          have chars := List.cons.inj (List.cons.inj same).2
          obtain ⟨tails, rests⟩ := ih bodyB chars.2
          exact ⟨by rw [chars.1, tails], rests⟩

private theorem atom_envelope (valid : decodeAtom text = some byte) : QuoteBody text := by
  unfold decodeAtom at valid
  split at valid
  · exact .escape .nil
  · exact .escape .nil
  · exact .escape .nil
  · rename_i a b c
    cases ob : octal b <;> simp_all
    cases oc : octal c <;> simp_all
    refine .escape (.plain ?_ ?_ (.plain ?_ ?_ .nil))
    · intro same; subst b; simp [octal] at ob
    · intro same; subst b; simp [octal] at ob
    · intro same; subst c; simp [octal] at oc
    · intro same; subst c; simp [octal] at oc
  · split at valid
    · rename_i allowed
      exact .plain allowed.2.2.1 allowed.2.2.2 .nil
    · contradiction
  · contradiction

theorem Fragments.envelope (fragments : Fragments text bytes) : QuoteBody text := by
  induction fragments with
  | nil => exact .nil
  | cons atom tail ih => exact (atom_envelope atom).append ih

def Quoted (text : List Char) : Prop :=
  ∃ body, text = '"' :: body ++ ['"'] ∧ QuoteBody body

theorem denotes_quoted (literal : Denotes text bytes) : Quoted text := by
  obtain ⟨body, payload, chars, fragments, value⟩ := literal
  exact ⟨body, chars, fragments.envelope⟩

theorem Quoted.boundary_unique (first : Quoted a) (second : Quoted b)
    (same : a ++ restA = b ++ restB) : a = b ∧ restA = restB := by
  obtain ⟨bodyA, textA, fragmentsA⟩ := first
  obtain ⟨bodyB, textB, fragmentsB⟩ := second
  rw [textA, textB] at same
  have bodies : bodyA ++ '"' :: restA = bodyB ++ '"' :: restB := by
    have trimmed : (bodyA ++ ['"']) ++ restA = (bodyB ++ ['"']) ++ restB :=
      (List.cons.inj same).2
    simpa only [List.append_assoc, List.singleton_append] using trimmed
  obtain ⟨texts, rests⟩ := fragmentsA.boundary_unique fragmentsB bodies
  exact ⟨by rw [textA, textB, texts], rests⟩

theorem quote_maximal (source : String) (candidate : Quoted text)
    (starts : text <+: (CTree.quote source).toList ++ rest) :
    text = (CTree.quote source).toList := by
  obtain ⟨after, same⟩ := starts
  exact (candidate.boundary_unique (denotes_quoted (quote_correct source)) same).1

end Rumoca.CString
