import RumocaFMI3.DeclaredMetadata
import ProofAudit.Audit

-- Axiom audit for the roots defined in RumocaFMI3.DeclaredMetadata.

#audit axioms Rumoca.FMI3.DeclaredMetadata.token_attribute
#audit axioms Rumoca.FMI3.DeclaredMetadata.modelName_attribute
#audit axioms Rumoca.FMI3.DeclaredMetadata.dimStarts_dimensions
#audit axioms Rumoca.FMI3.DeclaredMetadata.causalityText_ne
#audit axioms Rumoca.FMI3.DeclaredMetadata.exportedOf_value
#audit axioms Rumoca.FMI3.DeclaredMetadata.exportedOf_derivative
#audit axioms Rumoca.FMI3.DeclaredMetadata.entries_exported
#audit axioms Rumoca.FMI3.DeclaredMetadata.exported_interface
#audit axioms Rumoca.FMI3.DeclaredMetadata.digit_text_char
#audit axioms Rumoca.FMI3.DeclaredMetadata.text_toString
#audit axioms Rumoca.FMI3.DeclaredMetadata.text_append
#audit axioms Rumoca.FMI3.DeclaredMetadata.text_joined
#audit axioms Rumoca.FMI3.DeclaredMetadata.startValue_text
#audit axioms Rumoca.FMI3.DeclaredMetadata.timeName_text
#audit axioms Rumoca.FMI3.DeclaredMetadata.dimension_valid
#audit axioms Rumoca.FMI3.DeclaredMetadata.all_valid_of_forall
#audit axioms Rumoca.FMI3.DeclaredMetadata.dimensions_valid
#audit axioms Rumoca.FMI3.DeclaredMetadata.leaf_valid
#audit axioms Rumoca.FMI3.DeclaredMetadata.initialText_text
#audit axioms Rumoca.FMI3.DeclaredMetadata.causalityText_text
#audit axioms Rumoca.FMI3.DeclaredMetadata.valueAttributes_valid
#audit axioms Rumoca.FMI3.DeclaredMetadata.derivativeAttributes_valid
#audit axioms Rumoca.FMI3.DeclaredMetadata.variable_valid
#audit axioms Rumoca.FMI3.DeclaredMetadata.entries_declaration
#audit axioms Rumoca.FMI3.DeclaredMetadata.timeVariable_valid
#audit axioms Rumoca.FMI3.DeclaredMetadata.modelVariables_valid
#audit axioms Rumoca.FMI3.DeclaredMetadata.nodeAttributes_valid
#audit axioms Rumoca.FMI3.DeclaredMetadata.node_valid
#audit axioms Rumoca.FMI3.DeclaredMetadata.modelStructure_valid
#audit axioms Rumoca.FMI3.DeclaredMetadata.valid
#audit axioms Rumoca.FMI3.DeclaredMetadata.document
#audit axioms Rumoca.FMI3.DeclaredMetadata.entries_references
#audit axioms Rumoca.FMI3.DeclaredMetadata.filterMap_eq_map_of
#audit axioms Rumoca.FMI3.DeclaredMetadata.valueReferences_nodup
#audit axioms Rumoca.FMI3.DeclaredMetadata.variable_references
#audit axioms Rumoca.FMI3.DeclaredMetadata.dims_as_declared
#audit axioms Rumoca.FMI3.DeclaredMetadata.derivative_references_state
#audit axioms Rumoca.FMI3.DeclaredMetadata.derivative_order
#audit axioms Rumoca.FMI3.DeclaredMetadata.structure_references_declared
#audit axioms Rumoca.FMI3.DeclaredMetadata.referenceOf_declared
#audit axioms Rumoca.FMI3.DeclaredMetadata.dependencies_declared
#audit axioms Rumoca.FMI3.DeclaredMetadata.outputs_complete
#audit axioms Rumoca.FMI3.DeclaredMetadata.isOutput_iff
#audit axioms Rumoca.FMI3.DeclaredMetadata.stateDerivatives_complete
#audit axioms Rumoca.FMI3.DeclaredMetadata.initialUnknowns_complete
#audit axioms Rumoca.FMI3.DeclaredMetadata.isCalculated_iff
#audit axioms Rumoca.FMI3.DeclaredMetadata.state_exact
#audit axioms Rumoca.FMI3.DeclaredMetadata.entry_name
#audit axioms Rumoca.FMI3.DeclaredMetadata.entries_names
#audit axioms Rumoca.FMI3.DeclaredMetadata.variableNames_eq
#audit axioms Rumoca.FMI3.DeclaredMetadata.paren_derivativeName
#audit axioms Rumoca.FMI3.DeclaredMetadata.derivativeName_injective
#audit axioms Rumoca.FMI3.DeclaredMetadata.names_nodup
#audit axioms Rumoca.FMI3.DeclaredMetadata.entries_value
#audit axioms Rumoca.FMI3.DeclaredMetadata.referenceOf_isSome
#audit axioms Rumoca.FMI3.DeclaredMetadata.dependencies_complete
#audit axioms Rumoca.FMI3.DeclaredMetadata.variablesOf_eq
#audit axioms Rumoca.FMI3.DeclaredMetadata.structureOf_eq
#audit axioms Rumoca.FMI3.DeclaredMetadata.entry_reference
#audit axioms Rumoca.FMI3.DeclaredMetadata.node_reference
#audit axioms Rumoca.FMI3.DeclaredMetadata.valueAttributes_prefix
#audit axioms Rumoca.FMI3.DeclaredMetadata.variable_output
#audit axioms Rumoca.FMI3.DeclaredMetadata.variable_calculated
#audit axioms Rumoca.FMI3.DeclaredMetadata.variable_derivative
#audit axioms Rumoca.FMI3.DeclaredMetadata.outputs_rendered
#audit axioms Rumoca.FMI3.DeclaredMetadata.initialUnknowns_rendered
#audit axioms Rumoca.FMI3.DeclaredMetadata.stateDerivatives_rendered
#audit axioms Rumoca.FMI3.DeclaredMetadata.calculated_no_start
#audit axioms Rumoca.FMI3.DeclaredMetadata.startEntries_length
