import RumocaFMI3.TensorFloat64Access
import ProofAudit.Audit

-- Axiom audit for the roots defined in RumocaFMI3.TensorFloat64Access.

#audit axioms Rumoca.FMI3.TensorFloat64.reject_false
#audit axioms Rumoca.FMI3.TensorFloat64.branch_false
#audit axioms Rumoca.FMI3.TensorFloat64.branch_true
#audit axioms Rumoca.FMI3.TensorFloat64.declare_next
#audit axioms Rumoca.FMI3.TensorFloat64.run_append
#audit axioms Rumoca.FMI3.TensorFloat64.run_one
#audit axioms Rumoca.FMI3.TensorFloat64.vr0_cmp
#audit axioms Rumoca.FMI3.TensorFloat64.vr0_bne
#audit axioms Rumoca.FMI3.TensorFloat64.declare_step_e
#audit axioms Rumoca.FMI3.TensorFloat64.cbranch_false
#audit axioms Rumoca.FMI3.TensorFloat64.cbranch_true
#audit axioms Rumoca.FMI3.TensorFloat64.dispatch_chain
#audit axioms Rumoca.FMI3.TensorFloat64.dispatchChain_noDecl
#audit axioms Rumoca.FMI3.TensorFloat64.dispatch_noDecl
#audit axioms Rumoca.FMI3.TensorFloat64.dispatch_closed
#audit axioms Rumoca.FMI3.TensorFloat64.fail_noDecl
#audit axioms Rumoca.FMI3.TensorFloat64.basic_condition_eq
#audit axioms Rumoca.FMI3.TensorFloat64.getDispatch_noDecl
#audit axioms Rumoca.FMI3.TensorFloat64.getBody_closed
#audit axioms Rumoca.FMI3.TensorFloat64.tensorReads_noDecl
#audit axioms Rumoca.FMI3.TensorFloat64.basic_explicit_pass
#audit axioms Rumoca.FMI3.TensorFloat64.guard_reaches_for
#audit axioms Rumoca.FMI3.TensorFloat64.guard_reaches
#audit axioms Rumoca.FMI3.TensorFloat64.declares_reaches_for
#audit axioms Rumoca.FMI3.TensorFloat64.declares_reaches
#audit axioms Rumoca.FMI3.TensorFloat64.get_tail_reaches
#audit axioms Rumoca.FMI3.TensorFloat64.cvr0_cmp
#audit axioms Rumoca.FMI3.TensorFloat64.cvr0_ne
#audit axioms Rumoca.FMI3.TensorFloat64.cvr0_eq
#audit axioms Rumoca.FMI3.TensorFloat64.regionBase_zero
#audit axioms Rumoca.FMI3.TensorFloat64.eval_pointer
#audit axioms Rumoca.FMI3.TensorFloat64.dispatch_reaches
#audit axioms Rumoca.FMI3.TensorFloat64.stage_reaches
#audit axioms Rumoca.FMI3.TensorFloat64.get_reaches
#audit axioms Rumoca.FMI3.TensorFloat64.get_behaviors
#audit axioms Rumoca.FMI3.TensorFloat64.core_reads_time
#audit axioms Rumoca.FMI3.TensorFloat64.reads_time
#audit axioms Rumoca.FMI3.TensorFloat64.reads_output
#audit axioms Rumoca.FMI3.TensorFloat64.core_writable_state
#audit axioms Rumoca.FMI3.TensorFloat64.writable_state
#audit axioms Rumoca.FMI3.TensorFloat64.get_instance_behaviors_state
#audit axioms Rumoca.FMI3.TensorFloat64.get_instance_behaviors_input
#audit axioms Rumoca.FMI3.TensorFloat64.get_instance_behaviors_time
#audit axioms Rumoca.FMI3.TensorFloat64.rhs_read_enter
#audit axioms Rumoca.FMI3.TensorFloat64.jacobian_read_enter
#audit axioms Rumoca.FMI3.TensorFloat64.resume_discard
#audit axioms Rumoca.FMI3.TensorFloat64.get_deriv_reaches
#audit axioms Rumoca.FMI3.TensorFloat64.get_output_reaches
#audit axioms Rumoca.FMI3.TensorFloat64.validateBody_closed
#audit axioms Rumoca.FMI3.TensorFloat64.setDispatch_noDecl
#audit axioms Rumoca.FMI3.TensorFloat64.setBody_closed
#audit axioms Rumoca.FMI3.TensorFloat64.validate_step
#audit axioms Rumoca.FMI3.TensorFloat64.validate_reaches
#audit axioms Rumoca.FMI3.TensorFloat64.set_guard_reaches
#audit axioms Rumoca.FMI3.TensorFloat64.set_declares_reaches
#audit axioms Rumoca.FMI3.TensorFloat64.set_stage_reaches
#audit axioms Rumoca.FMI3.TensorFloat64.set_tail_reaches
#audit axioms Rumoca.FMI3.TensorFloat64.set_reaches
#audit axioms Rumoca.FMI3.TensorFloat64.set_behaviors
#audit axioms Rumoca.FMI3.TensorFloat64.fail_printable
#audit axioms Rumoca.FMI3.TensorFloat64.vr0_printable
#audit axioms Rumoca.FMI3.TensorFloat64.getBodyFor_printable
#audit axioms Rumoca.FMI3.TensorFloat64.setBodyFor_printable
#audit axioms Rumoca.FMI3.TensorFloat64.rhsCall_printable
#audit axioms Rumoca.FMI3.TensorFloat64.jacobianCall_printable
#audit axioms Rumoca.FMI3.TensorFloat64.tensorReads_printable
#audit axioms Rumoca.FMI3.TensorFloat64.dispatch_printable
#audit axioms Rumoca.FMI3.TensorFloat64.getDispatch_printable
#audit axioms Rumoca.FMI3.TensorFloat64.setDispatch_printable
#audit axioms Rumoca.FMI3.TensorFloat64.getBody_printable
#audit axioms Rumoca.FMI3.TensorFloat64.setBody_printable
#audit axioms Rumoca.FMI3.TensorFloat64.signature_printable
#audit axioms Rumoca.FMI3.TensorFloat64.getFunction_denotes
#audit axioms Rumoca.FMI3.TensorFloat64.setFunction_denotes
#audit axioms Rumoca.FMI3.TensorFloat64.dispatch_admits
#audit axioms Rumoca.FMI3.TensorFloat64.getDispatch_admits
#audit axioms Rumoca.FMI3.TensorFloat64.setDispatch_admits
#audit axioms Rumoca.FMI3.TensorFloat64.null_get_behaviors
#audit axioms Rumoca.FMI3.TensorFloat64.null_set_behaviors
#audit axioms Rumoca.FMI3.TensorFloat64.dispatch_fails
#audit axioms Rumoca.FMI3.TensorFloat64.get_fail_prefix
#audit axioms Rumoca.FMI3.TensorFloat64.set_fail_prefix
#audit axioms Rumoca.FMI3.TensorFloat64.get_fail_behaviors
#audit axioms Rumoca.FMI3.TensorFloat64.set_fail_behaviors
#audit axioms Rumoca.FMI3.TensorFloat64.inputWritableStore_writable
#audit axioms Rumoca.FMI3.TensorFloat64.set_instance_behaviors_state
#audit axioms Rumoca.FMI3.TensorFloat64.set_instance_behaviors_input
#audit axioms Rumoca.FMI3.TensorFloat64.set_preserves_other_instances
#audit axioms Rumoca.FMI3.TensorFloat64.get_contract
#audit axioms Rumoca.FMI3.TensorFloat64.set_contract
#audit axioms Rumoca.FMI3.TensorFloat64.basicReject
#audit axioms Rumoca.FMI3.TensorFloat64.validateBody
